# Configuraci\u00c3\u00b3n de Base de Datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/nomina_asistencia?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=itson

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Servidor
server.port=8080

# Inicialización de SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
